"""
Generated by Mapdex contracts codegen. DO NOT EDIT DIRECTLY.

The QGIS plugin is published standalone, so it vendors the parts of the
canonical Python bindings it uses rather than importing the contracts package.
This is a generated excerpt of packages/contracts/generated_python/contracts.py
-- the lines below are copied from it verbatim, not re-derived.

Add a symbol by naming it in packages/contracts/codegen/qgis_subset.go and
running `make gen`; do not hand-edit this file or paste into it.
"""


class BatchKind:
    GEOREFERENCE = "georeference"
    DIGITIZE_PARCELS = "digitize_parcels"
    VALIDATE_DELIVER = "validate_deliver"
    FULL_PIPELINE = "full_pipeline"


ERROR_REGISTRY = [
    {
        "code": "CONTENT_POLICY_ATTESTATION_REQUIRED",
        "type": "bad_request",
        "http": 422,
        "template": "An explicit content-policy acknowledgement is required for every upload or import session."
    },
    {
        "code": "CONTENT_POLICY_BLOCKED",
        "type": "validation",
        "http": 422,
        "template": "This content cannot be processed under the Mapdex Acceptable Use Policy."
    },
    {
        "code": "CONTENT_POLICY_UNAVAILABLE",
        "type": "system",
        "http": 503,
        "template": "Content policy authorization is temporarily unavailable; processing remains disabled."
    },
    {
        "code": "ACCOUNT_RESTRICTED_PENDING_REVIEW",
        "type": "auth",
        "http": 403,
        "template": "This account is restricted pending content policy review."
    },
    {
        "code": "BAD_REQUEST",
        "type": "bad_request",
        "http": 400,
        "template": "The request payload is invalid: {message}"
    },
    {
        "code": "PLAN_INVALID",
        "type": "bad_request",
        "http": 400,
        "template": "The workflow plan is invalid: {message}"
    },
    {
        "code": "AGENT_STEP_BUDGET_EXHAUSTED",
        "type": "processing",
        "http": 422,
        "template": "The assistant reached its step limit before it could finish adjusting this work. Everything that ran is kept; review it and continue."
    },
    {
        "code": "AGENT_PLAN_CHANGE_REQUIRES_CONFIRMATION",
        "type": "processing",
        "http": 422,
        "template": "Continuing this work needs a change that alters the risk of the run: {message}"
    },
    {
        "code": "UNSUPPORTED_FORMAT",
        "type": "bad_request",
        "http": 400,
        "template": "The format {format} is not supported."
    },
    {
        "code": "UNSUPPORTED_RASTER_PROFILE",
        "type": "validation",
        "http": 422,
        "template": "This page has no drawn content to extract; check that the intended page was selected and that the scan is not blank."
    },
    {
        "code": "GEOREFERENCE_REQUIRED",
        "type": "validation",
        "http": 422,
        "template": "The raster must be georeferenced with embedded metadata or control points before spatial extraction."
    },
    {
        "code": "INVALID_EXTRACTION_COMPONENTS",
        "type": "bad_request",
        "http": 400,
        "template": "The requested extraction components are invalid: {message}"
    },
    {
        "code": "GEOMETRY_INVALID",
        "type": "validation",
        "http": 422,
        "template": "Geometry validation failed with issues."
    },
    {
        "code": "NOT_FOUND",
        "type": "not_found",
        "http": 404,
        "template": "The requested resource was not found."
    },
    {
        "code": "UNAUTHORIZED",
        "type": "auth",
        "http": 401,
        "template": "Authentication is required to access this resource."
    },
    {
        "code": "FORBIDDEN",
        "type": "auth",
        "http": 403,
        "template": "Access to this resource is forbidden."
    },
    {
        "code": "INTERNAL_SYSTEM_ERROR",
        "type": "system",
        "http": 500,
        "template": "An unexpected system error occurred. Please contact support."
    },
    {
        "code": "WORKFLOW_EXECUTION_FAILED",
        "type": "processing",
        "http": 500,
        "template": "The workflow step {step_type} failed execution."
    },
    {
        "code": "PROCESSING_SERVICE_UNREACHABLE",
        "type": "system",
        "http": 503,
        "template": "The processing service address {address} could not be resolved. This is a deployment configuration fault and retrying will not clear it."
    },
    {
        "code": "UNAUTHENTICATED",
        "type": "auth",
        "http": 401,
        "template": "A valid API key is required: {message}"
    },
    {
        "code": "FORBIDDEN_SCOPE",
        "type": "auth",
        "http": 403,
        "template": "The API key is missing the required scope: {scope}"
    },
    {
        "code": "NO_DATA_PROVIDED",
        "type": "bad_request",
        "http": 400,
        "template": "No input data was provided for this run."
    },
    {
        "code": "UNKNOWN_TOOL",
        "type": "bad_request",
        "http": 404,
        "template": "The requested tool {tool} does not exist."
    },
    {
        "code": "AI_OUTPUT_INVALID",
        "type": "system",
        "http": 502,
        "template": "The planner returned output that could not be used: {message}"
    },
    {
        "code": "VALIDATION_FAILED",
        "type": "validation",
        "http": 422,
        "template": "Validation failed with blocking issues."
    },
    {
        "code": "INVALID_WORKFLOW",
        "type": "bad_request",
        "http": 400,
        "template": "The workflow plan is not a valid DAG: {message}"
    },
    {
        "code": "RATE_LIMITED",
        "type": "rate_limit",
        "http": 429,
        "template": "Rate limit exceeded. Retry after {retry_after}s."
    },
    {
        "code": "QUOTA_EXCEEDED",
        "type": "rate_limit",
        "http": 429,
        "template": "You have reached your usage limit for this period. Your limit resets at {reset_at}."
    },
    {
        "code": "IDEMPOTENCY_CONFLICT",
        "type": "conflict",
        "http": 409,
        "template": "This Idempotency-Key was already used with a different request body."
    },
    {
        "code": "VERSION_CONFLICT",
        "type": "conflict",
        "http": 409,
        "template": "The layer changed after this edit session started. Reload the layer and apply the edit again."
    },
    {
        "code": "MUTATION_NOT_REVERSIBLE",
        "type": "validation",
        "http": 422,
        "template": "This change was recorded but cannot be undone: {reason}"
    },
    {
        "code": "MUTATION_ALREADY_UNDONE",
        "type": "conflict",
        "http": 409,
        "template": "This change has already been undone."
    },
    {
        "code": "MUTATION_SUPERSEDED",
        "type": "conflict",
        "http": 409,
        "template": "The layer changed after this edit, so undoing it would discard later work. Undo the newer changes first."
    },
    {
        "code": "REFERENCE_AMBIGUOUS",
        "type": "conflict",
        "http": 409,
        "template": "More than one workspace object matches {label}."
    },
    {
        "code": "REFERENCE_RESOLUTION_FAILED",
        "type": "system",
        "http": 500,
        "template": "Workspace references could not be resolved."
    },
    {
        "code": "REFERENCE_UNAVAILABLE",
        "type": "not_found",
        "http": 404,
        "template": "A referenced workspace object is unavailable."
    },
    {
        "code": "PLACE_NOT_FOUND",
        "type": "not_found",
        "http": 404,
        "template": "No place matched the supplied location."
    },
    {
        "code": "PLACE_AMBIGUOUS",
        "type": "conflict",
        "http": 409,
        "template": "The supplied location requires clarification."
    },
    {
        "code": "ROUTING_UNAVAILABLE",
        "type": "processing",
        "http": 503,
        "template": "Routing is temporarily unavailable."
    },
    {
        "code": "PROVIDER_RATE_LIMITED",
        "type": "rate_limit",
        "http": 429,
        "template": "The location provider rate limit was reached."
    },
    {
        "code": "CRS_REQUIRED",
        "type": "validation",
        "http": 422,
        "template": "A known coordinate reference system is required for this operation."
    },
    {
        "code": "SPATIAL_LIMIT_EXCEEDED",
        "type": "bad_request",
        "http": 413,
        "template": "The spatial operation exceeds the configured limit."
    },
    {
        "code": "INSUFFICIENT_CREDITS",
        "type": "bad_request",
        "http": 402,
        "template": "Organization has insufficient credits balance to dispatch runs."
    },
    {
        "code": "GUEST_LIMIT_REACHED",
        "type": "rate_limit",
        "http": 402,
        "template": "Guest limit reached — sign up to continue."
    },
    {
        "code": "BATCH_ITEM_LIMIT_EXCEEDED",
        "type": "bad_request",
        "http": 422,
        "template": "The batch has {items} items, above the plan limit of {limit}."
    },
    {
        "code": "OUTPUT_NOT_MATERIALIZED",
        "type": "system",
        "http": 500,
        "template": "The step {step_type} produced output that was not materialized into a spatial layer."
    },
    {
        "code": "REMOTE_ACCESS_DENIED",
        "type": "auth",
        "http": 403,
        "template": "The remote service denied access. The endpoint may require authentication."
    },
    {
        "code": "REMOTE_URL_NOT_FOUND",
        "type": "not_found",
        "http": 404,
        "template": "The remote resource was not found."
    },
    {
        "code": "CONNECTOR_SERVICE_ERROR",
        "type": "processing",
        "http": 422,
        "template": "The connector encountered an error communicating with the remote service: {message}"
    },
    {
        "code": "CONNECTOR_PARSE_ERROR",
        "type": "processing",
        "http": 422,
        "template": "The connector could not parse the remote service response: {message}"
    },
    {
        "code": "LICENSE_REVIEW_REQUIRED",
        "type": "validation",
        "http": 422,
        "template": "This data source is disabled until its source-specific license and attribution requirements are reviewed."
    },
    {
        "code": "ATTRIBUTION_PERSIST_FAILED",
        "type": "system",
        "http": 500,
        "template": "Required source attribution could not be preserved, so the export was stopped."
    },
    {
        "code": "DELIVERY_BLOCKED_BY_QUALITY",
        "type": "validation",
        "http": 422,
        "template": "Validation found blocking issues in this dataset, so the export was stopped. Repair or review the findings, then export again."
    },
    {
        "code": "MERGE_COUNT_MISMATCH",
        "type": "processing",
        "http": 500,
        "template": "The merged dataset does not contain the same number of features as its sources, so it was discarded rather than delivered."
    },
    {
        "code": "DELIVERY_BLOCKED_UNVERIFIED_REPAIR",
        "type": "validation",
        "http": 422,
        "template": "This dataset was repaired but not re-checked afterwards, so its quality is unknown. Validate it again, then export."
    },
    {
        "code": "CONNECTION_DISCOVERY_FAILED",
        "type": "validation",
        "http": 422,
        "template": "Could not browse the connection: {message}"
    },
    {
        "code": "CONNECTION_DISCOVERY_UNSUPPORTED",
        "type": "validation",
        "http": 422,
        "template": "Browsing is not yet supported for this connection type."
    },
    {
        "code": "CONNECTION_CREDENTIALS_REQUIRED",
        "type": "validation",
        "http": 422,
        "template": "Browsing this connection type requires stored credentials, which are not yet supported."
    },
    {
        "code": "CONNECTION_IMPORT_UNSUPPORTED",
        "type": "validation",
        "http": 422,
        "template": "Importing is not supported for this connection type."
    },
    {
        "code": "CONNECTION_IMPORT_FAILED",
        "type": "validation",
        "http": 422,
        "template": "Could not import from the connection: {message}"
    },
    {
        "code": "CONNECTION_IMPORT_EMPTY",
        "type": "validation",
        "http": 422,
        "template": "The selected resource returned no features to import."
    },
    {
        "code": "CONNECTION_QUERY_REFUSED",
        "type": "validation",
        "http": 422,
        "template": "That question cannot be asked of this table: {message}"
    },
    {
        "code": "CONNECTION_QUERY_FAILED",
        "type": "validation",
        "http": 422,
        "template": "The database could not answer the question: {message}"
    }
]
