"""Vendor the canonical Nivo system prompt into the plugin.

QGIS and the Mapdex workspace must drive the agent from the same contract, so
the prompt has one source of truth in packages/ai-prompts and the plugin ships a
generated copy. Run this after editing the prompt; tests/test_vendored_prompt.py
fails when the copy drifts.

Usage: python3 scripts/vendor_prompt.py
"""
from __future__ import annotations

import json
import pathlib

PLUGIN_ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = PLUGIN_ROOT.parents[1] / "packages" / "ai-prompts" / "prompts" / "nivo.system.md"
TARGET = PLUGIN_ROOT / "mapdex_qgis" / "nivo_prompt.py"

HEADER = '''"""Vendored copy of the canonical Nivo system prompt.

The source of truth is packages/ai-prompts/prompts/nivo.system.md. QGIS and the
Mapdex workspace must drive the agent from the SAME contract, otherwise the two
surfaces answer the same question differently and neither is reproducible.
tests/test_vendored_prompt.py fails if this copy drifts.

Do not edit this file. Edit the prompt, bump its version and its eval manifest,
then re-run scripts/vendor_prompt.py.
"""
from __future__ import annotations

CLIENT_PLACEHOLDER = "{{CLIENT_NAME}}"

# The prompt body, without the registry front matter (version, evals, budget),
# which is server-side bookkeeping the desktop does not need.
NIVO_SYSTEM_PROMPT = {body}


def system_prompt(client_name: str) -> str:
    """The shared contract, named for the client it is running in."""
    return NIVO_SYSTEM_PROMPT.replace(CLIENT_PLACEHOLDER, client_name)
'''


def prompt_body(text: str) -> str:
    """Strip the YAML front matter and return the prompt itself."""
    if text.startswith("---"):
        return text.split("---", 2)[2].lstrip("\n")
    return text


def main() -> int:
    body = prompt_body(SOURCE.read_text(encoding="utf-8"))
    # json.dumps produces a valid, fully escaped Python string literal for any
    # content, which hand-rolled quoting does not.
    TARGET.write_text(HEADER.format(body=json.dumps(body)), encoding="utf-8")
    print("vendored {} characters into {}".format(len(body), TARGET.name))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
